if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(RIOT_ARCH_X64 1)
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(RIOT_ARCH_X86 1)
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "^armv7")
    set(RIOT_ARCH_ARM 1)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^aarch64")
    set(RIOT_ARCH_ARM64 1)
else()
    message(FATAL_ERROR "Unsupported architecture")
    return()
endif()

message(STATUS "Detected Architecture: ${CMAKE_SYSTEM_PROCESSOR}")