if (NOT DEFINED IMPACT_ROOT_DIR)
    message(FATAL_ERROR "IMPACT_ROOT_DIR is not defined!")
endif ()

# detect our OS
# TODO: Figure out how to detect if we're on the switch or not.
if(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
    if(XBOX_CONSOLE_TARGET MATCHES "scarlett" OR XBOX_CONSOLE_TARGET MATCHES "xboxone") # TODO: This may not work. Verify once I have access to xbox docs.
        set(IMPACT_OS_XBOX 1)
        if (XBOX_CONSOLE_TARGET MATCHES "scarlett")
            set(IMPACT_OS_XBOX_SCARLETT 1)
        else()
            set(IMPACT_OS_XBOX_XBOXONE 1)
        endif()
    else()
        set(IMPACT_OS_WINDOWS 1)
    endif()
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "WindowsStore")
    set(IMPACT_OS_WINRT 1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    set(IMPACT_OS_LINUX 1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
    set(IMPACT_OS_MACOS 1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "iOS")
    set(IMPACT_OS_IOS 1)
    # As we want to find packages in our bin folder too
    # we need to tell CMake we want to search there instead
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Android")
    set(IMPACT_OS_ANDROID 1)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "^Orbis$" OR ${CMAKE_SYSTEM_NAME} MATCHES "^Prospero$" ) # TODO: This may not work. Verify once I have access to ps4 docs.
    set(IMPACT_OS_PSX 1)
    if (${CMAKE_SYSTEM_NAME} MATCHES "^Prospero$")
        set(IMPACT_OS_PSX_PROSPERO 1)
    else ()
        set(IMPACT_OS_PSX_ORBIS 1)
    endif()
elseif(CMAKE_SYSTEM_NAME MATCHES "^k?FreeBSD$")
    set(IMPACT_OS_FREEBSD 1)
elseif(CMAKE_SYSTEM_NAME MATCHES "^OpenBSD$")
    set(IMPACT_OS_OPENBSD 1)
elseif(CMAKE_SYSTEM_NAME MATCHES "^NetBSD$")
    set(IMPACT_OS_NETBSD 1)

else()
    message(FATAL_ERROR "Unsupported OS: ${CMAKE_SYSTEM_NAME}")
endif()

message(STATUS "Detected Operating system: ${CMAKE_SYSTEM_NAME}")